"""
core/state.py
────────────────────────────────────────────────────────────────────────────────
BMADState TypedDict — shared state passed through every node in the LangGraph
StateGraph.

All 15 original AgentState fields are preserved verbatim so existing LangGraph
node signatures (state: dict) continue to work without modification.

Four new BMAD-specific fields are appended:
  session_id      — UUID4 string generated by observability.create_session()
  pipeline_status — coarse lifecycle flag read by pipeline_ui.py
  agent_log       — list of AgentCallRecord objects from observability.py
  output_dir      — per-session archive path set by executor_agent.py

The old AgentState name is re-exported as an alias so any remaining imports
of ``from state import AgentState`` continue to resolve without changes.
────────────────────────────────────────────────────────────────────────────────
"""

from __future__ import annotations

from typing import Any, List, Optional, TypedDict


class BMADState(TypedDict):
    # ── Original 15 fields — do NOT reorder or rename ─────────────────────
    user_request: str
    functional_spec: Optional[str]
    technical_design: Optional[str]
    code: Optional[str]
    test_cases: Optional[str]
    review_feedback: Optional[str]
    review_approved: Optional[bool]
    review_attempts: Optional[int]
    validation_passed: Optional[bool]
    validation_error: Optional[str]
    validation_attempts: Optional[int]
    execution_result: Optional[str]
    execution_error: Optional[str]
    langfuse_handler: Optional[Any]   # langfuse.langchain.CallbackHandler | None
    test_file: Optional[str]

    # ── New BMAD fields ────────────────────────────────────────────────────
    session_id: Optional[str]
    pipeline_status: Optional[str]    # "running" | "complete" | "failed"
    agent_log: Optional[List[Any]]    # List[AgentCallRecord] — see observability.py
    output_dir: Optional[str]         # absolute path to per-session archive dir
    refined_prompt: Optional[str]     # PromptRefiner output; Planner reads this first


# Backward-compatibility alias — keeps ``from state import AgentState`` working
AgentState = BMADState
